version: "2.1"
services:
  scrutiny:
    image: lscr.io/linuxserver/scrutiny:latest
    container_name: scrutiny
    cap_add:
      - SYS_RAWIO
      - SYS_ADMIN #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Zurich
      - SCRUTINY_API_ENDPOINT=http://localhost:8080
      - SCRUTINY_WEB=true
      - SCRUTINY_COLLECTOR=true
    volumes:
      - /portainer/Files/AppData/Config/scrutiny/config:/config
      - /run/udev:/run/udev:ro
    ports:
      - 8787:8080
    devices:
      - /dev/sda:/dev/sda
      - /dev/sdb:/dev/sdb
    restart: unless-stopped
